---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    default_attribute_whitelist: []
    normal_attribute_whitelist: []

platforms:
  - name: centos-7.2
    driver:
      box: bento/centos-7.2

suites:
  - name: default
    run_list:
      - recipe[hg_sas3ircu::default]
    attributes:
